apiVersion: v1
kind: Service
metadata:
  name: herofishing-matchmaker
  namespace: herofishing-matchserver
  labels:
    app: herofishing-matchmaker
spec:
  type: LoadBalancer
  selector:
    app: herofishing-matchmaker
  ports:
    - protocol: TCP
      port: 32680
      targetPort: 30390
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-server-deployment-30390
  namespace: herofishing-matchserver
spec:
  selector:
    matchLabels:
      app: herofishing-matchmaker
  replicas: 1
  template:
    metadata:
      labels:
        app: herofishing-matchmaker
    spec:
      containers:
      - name: herofishing-matchmaker
        image: asia-east1-docker.pkg.dev/aurafortest/herofishing/herofishing-matchmaker:0.1.17
        resources:
          requests:
            memory: "1024Mi"
            cpu: "100m"
          limits:
            memory: "2048Mi"
            cpu: "200m"
        env:
        - name: "PORT"
          value: "30390"
        - name: "Env"
          value: "Dev"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "MongoAPIPublicKey"
          value: "rqjseyja" #之後要搬其他位置放
        - name: "MongoAPIPrivateKey" 
          value: "e8cc1224-f04b-46c7-aee0-19309dc499dc" #之後要搬其他位置放
        - name: "MongoUser"
          value: "tester"
        - name: "MongoPW"
          value: "test123"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: herofishing-matchmaker-autoscaler
  namespace: herofishing-matchserver
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: game-server-deployment-30390
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
