apiVersion: v1
kind: Service
metadata:
  name: herofishing-lobby-service
  namespace: herofishing-service
spec:
  type: LoadBalancer
  selector:
    app: herofishing-lobby
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: herofishing-lobby
  namespace: herofishing-service
spec:
  selector:
    matchLabels:
      app: herofishing-lobby
  replicas: 1
  template:
    metadata:
      labels:
        app: herofishing-lobby
        type: herofishing-lobby  # 標示為herofishing-service, 方便之後對版本做刪除等管理
        imgVersion: "0.1.16"       # 加版本標籤, 未來方便針對某個版本進行移除也要連agones產生的gameserver一起移除, 版本必須要跟image版本一致
    spec:
      containers:
      - name: herofishing-lobby
        image: asia-east1-docker.pkg.dev/herofishing-dev/herofishing/herofishing-lobby:0.1.16
        resources:
          requests:
            memory: "1024Mi"
            cpu: "100m"
          limits:
            memory: "2048Mi"
            cpu: "200m"
        # 環境變數設定
        env:
        - name: "Env"
          value: "Dev"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name              
        # mongodb相關
        - name: MongoAPIPublicKey
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MongoAPIPublicKey
        - name: MongoAPIPrivateKey
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MongoAPIPrivateKey
        - name: MongoUser
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MongoUser
        - name: MongoPW
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MongoPW
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: herofishing-lobby-autoscaler
  namespace: herofishing-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: herofishing-lobby
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: herofishing-certification
  namespace: herofishing-service
spec:
  secretName: herofishing-service-tls
  issuerRef:
    name: herofishing-cert-issuer
    kind: ClusterIssuer
  commonName: 'aurafordev.com'
  dnsNames:
  - 'aurafordev.com'
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: herofishing-ingress
  namespace: herofishing-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "herofishing-cert-issuer"
spec:
  tls:
  - hosts:
    - aurafordev.com
    secretName: herofishing-service-tls
  rules:
  - host: aurafordev.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: herofishing-lobby-service
            port:
              number: 80