apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: herofishing-cert-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: aurafordev@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: herofishing-certification
  namespace: herofishing-service
spec:
  secretName: herofishing-service-tls
  issuerRef:
    name: herofishing-cert-issuer
    kind: ClusterIssuer
  commonName: 'aurafordev.com'
  dnsNames:
  - 'aurafordev.com'
